# permissions for end users to view externalhaproxies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: externalhaproxy-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: external-haproxy
    app.kubernetes.io/part-of: external-haproxy
    app.kubernetes.io/managed-by: kustomize
  name: externalhaproxy-viewer-role
rules:
- apiGroups:
  - haproxy.bitmedia.co.jp
  resources:
  - externalhaproxies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - haproxy.bitmedia.co.jp
  resources:
  - externalhaproxies/status
  verbs:
  - get
