---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - haproxy.bitmedia.co.jp
  resources:
  - externalhaproxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - haproxy.bitmedia.co.jp
  resources:
  - externalhaproxies/finalizers
  verbs:
  - update
- apiGroups:
  - haproxy.bitmedia.co.jp
  resources:
  - externalhaproxies/status
  verbs:
  - get
  - patch
  - update
