# permissions for end users to edit tcpbackends.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: tcpbackend-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: external-haproxy
    app.kubernetes.io/part-of: external-haproxy
    app.kubernetes.io/managed-by: kustomize
  name: tcpbackend-editor-role
rules:
- apiGroups:
  - haproxy.bitmedia.co.jp
  resources:
  - tcpbackends
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - haproxy.bitmedia.co.jp
  resources:
  - tcpbackends/status
  verbs:
  - get
