---
- name: Prerequisites
  become: true
  apt:
    name:
      - software-properties-common

- name: Install HAProxy 1/3
  become: true
  apt_repository:
    repo: ppa:vbernat/haproxy-2.6

- name: Install HAProxy 2/3
  become: true
  apt:
    name:
      - haproxy=2.6.7-1ppa1~focal

- name: Install HAProxy 3/3
  become: true
  dpkg_selections:
    name: haproxy
    selection: hold
