//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackendServer) DeepCopyInto(out *BackendServer) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendServer.
func (in *BackendServer) DeepCopy() *BackendServer {
	if in == nil {
		return nil
	}
	out := new(BackendServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataPlaneAPI) DeepCopyInto(out *DataPlaneAPI) {
	*out = *in
	out.BasicAuthSecret = in.BasicAuthSecret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataPlaneAPI.
func (in *DataPlaneAPI) DeepCopy() *DataPlaneAPI {
	if in == nil {
		return nil
	}
	out := new(DataPlaneAPI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalHAProxy) DeepCopyInto(out *ExternalHAProxy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalHAProxy.
func (in *ExternalHAProxy) DeepCopy() *ExternalHAProxy {
	if in == nil {
		return nil
	}
	out := new(ExternalHAProxy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExternalHAProxy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalHAProxyList) DeepCopyInto(out *ExternalHAProxyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ExternalHAProxy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalHAProxyList.
func (in *ExternalHAProxyList) DeepCopy() *ExternalHAProxyList {
	if in == nil {
		return nil
	}
	out := new(ExternalHAProxyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExternalHAProxyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalHAProxySpec) DeepCopyInto(out *ExternalHAProxySpec) {
	*out = *in
	out.DataPlaneAPI = in.DataPlaneAPI
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalHAProxySpec.
func (in *ExternalHAProxySpec) DeepCopy() *ExternalHAProxySpec {
	if in == nil {
		return nil
	}
	out := new(ExternalHAProxySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalHAProxyStatus) DeepCopyInto(out *ExternalHAProxyStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalHAProxyStatus.
func (in *ExternalHAProxyStatus) DeepCopy() *ExternalHAProxyStatus {
	if in == nil {
		return nil
	}
	out := new(ExternalHAProxyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCPBackend) DeepCopyInto(out *TCPBackend) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TCPBackend.
func (in *TCPBackend) DeepCopy() *TCPBackend {
	if in == nil {
		return nil
	}
	out := new(TCPBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TCPBackend) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCPBackendList) DeepCopyInto(out *TCPBackendList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TCPBackend, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TCPBackendList.
func (in *TCPBackendList) DeepCopy() *TCPBackendList {
	if in == nil {
		return nil
	}
	out := new(TCPBackendList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TCPBackendList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCPBackendSpec) DeepCopyInto(out *TCPBackendSpec) {
	*out = *in
	out.HAProxy = in.HAProxy
	if in.Servers != nil {
		in, out := &in.Servers, &out.Servers
		*out = make([]BackendServer, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TCPBackendSpec.
func (in *TCPBackendSpec) DeepCopy() *TCPBackendSpec {
	if in == nil {
		return nil
	}
	out := new(TCPBackendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCPBackendStatus) DeepCopyInto(out *TCPBackendStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TCPBackendStatus.
func (in *TCPBackendStatus) DeepCopy() *TCPBackendStatus {
	if in == nil {
		return nil
	}
	out := new(TCPBackendStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCPFrontend) DeepCopyInto(out *TCPFrontend) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TCPFrontend.
func (in *TCPFrontend) DeepCopy() *TCPFrontend {
	if in == nil {
		return nil
	}
	out := new(TCPFrontend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TCPFrontend) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCPFrontendList) DeepCopyInto(out *TCPFrontendList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TCPFrontend, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TCPFrontendList.
func (in *TCPFrontendList) DeepCopy() *TCPFrontendList {
	if in == nil {
		return nil
	}
	out := new(TCPFrontendList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TCPFrontendList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCPFrontendSpec) DeepCopyInto(out *TCPFrontendSpec) {
	*out = *in
	out.HAProxy = in.HAProxy
	if in.Binds != nil {
		in, out := &in.Binds, &out.Binds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Backend = in.Backend
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TCPFrontendSpec.
func (in *TCPFrontendSpec) DeepCopy() *TCPFrontendSpec {
	if in == nil {
		return nil
	}
	out := new(TCPFrontendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCPFrontendStatus) DeepCopyInto(out *TCPFrontendStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TCPFrontendStatus.
func (in *TCPFrontendStatus) DeepCopy() *TCPFrontendStatus {
	if in == nil {
		return nil
	}
	out := new(TCPFrontendStatus)
	in.DeepCopyInto(out)
	return out
}
